version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...
    - find internal/server/web/dist -mindepth 1 ! -name '.gitkeep' -delete 2>/dev/null || true
    - cp -r web/dist/* internal/server/web/dist/ 2>/dev/null || true

builds:
  - id: kassie
    main: ./cmd/kassie
    binary: kassie
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/KashifKhn/kassie/internal/shared/version.Version={{.Version}}
      - -X github.com/KashifKhn/kassie/internal/shared/version.Commit={{.Commit}}
      - -X github.com/KashifKhn/kassie/internal/shared/version.BuildDate={{.Date}}
    hooks:
      post:
        - find internal/server/web/dist -mindepth 1 ! -name '.gitkeep' -delete 2>/dev/null || true

archives:
  - id: kassie
    format: tar.gz
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
